buildscript {
  repositories {
    mavenCentral()
    gradlePluginPortal()
    mavenLocal()
    google()
    maven { url = 'https://central.sonatype.com/repository/maven-snapshots/' }
  }
  dependencies {


  }
}

allprojects {
  apply plugin: 'eclipse'
  apply plugin: 'idea'

  // This allows you to "Build and run using IntelliJ IDEA", an option in IDEA's Settings.
  idea {
    module {
      outputDir = file('build/classes/java/main')
      testOutputDir = file('build/classes/java/test')
    }
  }
}

configure(subprojects) {
  apply plugin: 'java-library'
  java.sourceCompatibility = 21
  java.targetCompatibility = 21


  def encryptedAssetsDir = file("assets-encrypted")
  def sourceAssetsDir = project.rootProject.file('assets').absolutePath

  tasks.register('encryptAssets', JavaExec) {
    group = 'build'
    description = '加密 assets 资源'
    dependsOn 'classes'
    inputs.dir sourceAssetsDir
    outputs.dir encryptedAssetsDir
    doFirst {
      if (encryptedAssetsDir.exists()) delete encryptedAssetsDir
      classpath = sourceSets.main.runtimeClasspath
      mainClass = 'xyz.zzzxb.toolkit.security.FileEncryptor'
      args = [sourceAssetsDir,
              encryptedAssetsDir.absolutePath,
              "--exclude=*.otf"
//            "--include=*.png,*.jpg"
      ]
    }
  }

  // From https://lyze.dev/2021/04/29/libGDX-Internal-Assets-List/
  // The article can be helpful when using assets.txt in your project.
  tasks.register('generateAssetList') {
    inputs.dir("${project.rootDir}/assets/")
    // projectFolder/assets
    File assetsFolder = new File("${project.rootDir}/assets/")
    // projectFolder/assets/assets.txt
    File assetsFile = new File(assetsFolder, "assets.txt")
    // delete that file in case we've already created it
    assetsFile.delete()

    // iterate through all files inside that folder
    // convert it to a relative path
    // and append it to the file assets.txt
    fileTree(assetsFolder).collect { assetsFolder.relativePath(it) }.sort().each {
      assetsFile.append(it + "\n")
    }
  }
  processResources.dependsOn 'generateAssetList'

  compileJava {
    options.incremental = true
  }
}

subprojects {
  version = "$projectVersion"
  ext.appName = 'gdx-toolkit-sandbox'
  repositories {
    mavenCentral()
    // You may want to remove the following line if you have errors downloading dependencies.
    mavenLocal()
    maven { url = 'https://central.sonatype.com/repository/maven-snapshots/' }
    maven { url = 'https://jitpack.io' }
  }
}

eclipse.project.name = 'gdx-toolkit-sandbox' + '-parent'
